# Esta linha desativa a op√ß√£o de criar uma issue em branco.
blank_issues_enabled: false

# (Opcional) Voc√™ pode adicionar links para documenta√ß√£o externa ou f√≥runs de discuss√£o.
# Se um usu√°rio n√£o souber qual template usar, ele ver√° estes links.
contact_links:
  - name: Ì¥î D√∫vidas Gerais
    url: https://github.com/etroquei # Link para a p√°gina principal da organiza√ß√£o ou um reposit√≥rio de discuss√µes
    about: Por favor, use este canal para perguntas que n√£o se encaixam nos templates.
